label day4Solis:
    "I hope the experiment went well, I can't imagine having to deal with those bees again."
    "After leaving the herbs to marinate for the night it was now time to go see how they've developed."
    "Stumbling out of the room, I make my way to the green room."
    "Half way there, I stumble into Summer who'd seem to have been waiting for me."

    "I greet Summer, nervously as I had realized I had been late to our agreed time."
    s "What the heck [name], you're late. What took you so long?"
    "I try to explain to her how the demons had attacked me in my bed, while in truth I had just slept past my alarm."
    s "Demons? Oh No! Are you okay? Are you hurt? Why didn't you tell me earlier?"
    "A sense of guilt washses over me as I hesitate from her sudden concern."
    "I tell her the truth, she sighs and puffs up her cheeks in anger."

    s "Don't worry me like that again, okay? I really thought you got harassed by demons."
    "I chuckle, telling her how demons aren't real. She looks at me with concern."
    s "What do you mean... demons are real...."
    "There's a silence between us for a moment."
    s "Anyways, lets go check on the herbs in the garden I'm sure it was a success."

    "We head towards the green house."
    "As we enter the green house we notice a figure inspecting our herbs."
    "I had seen her in the green house before, though I wasn't too sure who she was."
    "A little cautious, I began to approach her. Ready to confront her meddling."
    s "Wait! That's Professor Tasha, she's the one who let us use the green house for our experiment."

    "Tasha turns around, smiling as she noticed the two of us."
    t "Well well well, if it isn't my dear sunshine. How is it going?"
    "She smiles as she hugs Summer who's a little hesitant from the sudden embracement."
    s "Hey professor Tasha, we're doing... great."
    "Tasha lets go of Summer allowing her to finally breath again."
    t "I was just looking at your experiment, quite an excellent job marinating the herbs. You've even managed to get all the chlorophyll out."
    "Summer and I look at the leaves, which now appeared transparent."

    t "And your concoction as well, I haven't seen a Cloying crumble this perfect in centuries."
    "Summer blushes a little, the waves of compliments lighting up her cheeks."
    t "Since your project seems to be completed, could I ask you a small favor Summer?"
    s "Sure thing Professor Tasha, what can I help you with?"
    "Tasha explains how the mandrakes she had sent to set up for the Amphitheater had withered and how she needs help setting up for the banquet."
    s "I wholeheartedly agrees though she seems to make no effort in asking you for help."

    "What do you do? On the one hand Summer hadn't directly asked you for help."
    "But on the other it would take her the whole day to set up for  the banquet."
    menu:
        "I'll be right back.":
            "I head towards the Amphitheater."
            "There's a performance that seems to be wrapping up at the theater."
            m "Hello fellow Solis student."
            "Professor Morgana of House Luna appears behind me."
            char "Ah, Professor Morgana!"
            m "May I help you?"
            char "Well actually we need help setting up for the banquet to bring things over here."
            e "We?"
            "The performer who had been on stage shows up beside Professor Morgana."
            e "I bet it's Summer trying to work on arrangements by herself."
            m "I suppose it's quite in character for her."
            m "You'd know best, Eluna."
            jump day4SolisExtraPath
        "Do you need any help?":
            s "Thanks [name], though I'm not sure how much we can do with just the two of us."
            s "But I really appreciate that you're willing to help me."
            "It took a decent amount of time, but we got the work done early."
            "The sun's nearly set as we finish loading the final pot onto the cart."
            s "Oof, I think that was the last of them, it took longer then expected didn't it."
            s "Thanks for helping me out [name]."
            "Summer begins to mumble to herself: though it would've been faster if I had magical abilities."
            "My body is killing me after all that."
            jump day4SolisEnd
        "Good luck, Summer!":
            "Summer smiles at you, sighing as she prepares to get back to work."
            "Realizing my prank didn't get through, I quickly go to help her out."
            "We work diligently, though there's any talk between us."
            "As we finish setting up for the banquet we hear the performers over at the Amphitheater."
            s "That must've been the folks at the house of Luna."
            "I realize that perhaps I could've asked them for help, but it was too late for that."
            s "Well, thanks for your help [name] I couldn't have done this without you."
            jump day4SolisEnd

label day4SolisExtraPath:
    e "Where is Summer right now?"
    e "I've just about wrapped up rehearsal, I can manage helping out a friend."
    m "Go with [name] to manage with Summer."
    e "Let's go."
    e "I assume she's at the Greenhouse?"
    "I nod, startled by the intensity of Eluna's call to action."
    "Eluna walks off briskly."
    "I trail after her."

    "We show up at the Greenhouse."
    "I'm nearly out of breath, but Eluna still seems to be fine."
    "Summer is grunting, lifting up heavy pots onto a small wagon."
    e "Summer!"
    s "Oh! Hiya Eluna! What brings you here?"
    e "What brings me here? I'm here to help you out."
    e "What gives you the idea that you need to be doing all this heavy lifting yourself!?"
    s "It's not a big deal, really."
    e "You're going to break your back lifting all these pots and decor alone."
    e "You're here at the academy now."
    e "You don't have to keep doing things alone."
    s "..."
    e "Come on, [name], let's lift these together."

    #Time skip.
    "Summer and I wave goodbye to Eluna and the other Luna students who came to help."
    "Summer sighs in exhaustion."
    s "Well, I sure am glad at least we managed to finish all the preparations today."
    s "I really have to go thank Eluna and the other students of Luna."
    s "..."
    s "Hey, [name]?"
    char "Yeah?"
    s "I really appreciate you reaching out to the Luna students and helping me out."
    s "I guess I have a bad habit of not really asking for help."
    s "You see..."
    s "I didn't grow up glamorous or with a lot of magical abilities to spare."
    if(perfectRun){
        s "Instead it almost felt as if all our families magical talent went to my sister."
        s "She was perfect in every way, she was strong, magical, and beautiful."
        s "While I'm... this."
        s "While she was nice to me, my parents weren't the same. They only saw her, and I was labeled a failure."
        s "Sometimes I wondered if I was even a part of this family."
        s "Maybe I was a little scared they'd abandon me."
        s "So I'd work alone, if I could do everything myself I would be successful right?"
        s "Eluna was the first to notice, we knew each other since we were little."
        s "She used to help me out anytime I'd try to do anything alone, but she moved away when we were 10."
        "Summer begins to cry as she recounts the countless of times she's felt like a failure, even though it's clearly she's pushing herself past her limit."
        s "I guess what I wanted to say was... thank you, I would've probably passed out from exhaustion if you hadn't helped me out."
        s "heh, that sounds a little weird when you think about it, I know what I'm doing wrong but I still can't fix it."
        s "But as a token of thanks, I wanted to give you this."
        "She hands you a bouquet of dried flowers, all still perfectly preserved with their beauty."
        s "It's sunflowers, my favorite flower."
        s "I've always wanted to be like a sunflower, someone who's bright and loved by everyone."
        s "I hope I did a good job at that."
        "She smiled, a slight glow emitting from her body, a sign she'd let her soul free."
    }else{
        s "Actually, never mind, this isn't the right time to tell you"
    }

label day4SolisEnd:
    s "Let's go grab some food, I'm starving after all that work!"
    #transition to Commons
    "Summer and I had a big meal in the cafeteria."
    "The both of us were so tired we walked back to the Commons in peaceful silence."