define e = Character('Eluna', color='#f7c039')
define m = Character('Morganna', color='#ba1230')
define char = Character("name", dynamic=True, color='#f933ff')

label day4Luna:
    #"Today is the final rehearsal for the Full Moon Ritual"

    "It's nice and early, about 30 minutes before I need to be at the Amphitheater"
    "Today is supposed to be the final rehearsal for the Full Moon Ritual"
    "Even though it's only been a few days for me at Luminoire Academy..."
    "It's been quite the experience so far!"
    "I head over to the Amphitheater..."

    "Eluna's already here, practicing her lines."
    "A few other students are already here too..."
    "Uh oh... did I arrive late somehow?"
    m "No, you didn't."
    char "Professor Morgana! I didn't notice you there."
    m "It's alright. There was something I wanted to talk to you about."

    m "I know you aren't aware of Eluna's family name and bloodline."
    m "She doesn't exactly make it clear wth many of her peers"
    m "She's always preferred to be on the down-low about these matters."
    m "Eluna comes from a prestigious family line of witches."
    m "I was tasked to ensure that her magical prowess would be maximized."
    m "-and to not allow any potential distractions to her success."
    m "I think it's good that you and Eluna have befriended each other and have become so close."
    m "I'm sure Eluna appreciates you as well."
    m "But she has been spending much of her free time with you instead of practicing her magic."
    m "[name], I know you mean well but-"
    m "Do not distract Eluna from her destiny."
    m "Understood?"

    "I quietly stare back at Professor Morgana."
    "Am I... holding Eluna back?"
    "How would Professor Morgana know what's best for Eluna?"
    "Has she even bothered to ask Eluna?"
    "Before I could respond-"
    m "I know you must feel defensive over Eluna's autonomy."
    m "If I had a choice, I would want Eluna to explore and have a richer experience of her youth."  
    m "However, both Eluna and I understand how important her role to her family is." #How important her role is to her family?
    m "I implore you to understand as well."
    
    char "I see..."
    "Seems like Eluna's under a lot of pressure nonetheless."
    "But I don't want to be an interference to Eluna's success-"
    "And her future."
    "From behind me I hear applause."
    "Eluna must be done with her rehearsal"
    e "[name]!"
    "I turn and see her beeline towards me."
    "I can feel Professor Morgana's piercing gaze..."

    e "I noticed you arrived a little earlier today."
    e "Worried Professor Morgana would give you a hard time?"
    m "That should hardly be an issue."
    m "I should go greet the rest of the class."
    "Morgana begins to walk towards the rest of the calss, but then pauses next to me." #Professor Morgana? Because in most of the other messages we address her as such
    "She quietly speaks to me-"
    m "Remember what I told you."
    "She heads towards the rest of the class briskly."
    e "I hope Professor hasn't been giving you a hard time."
    e "She really does mean well."
    e "Are you free soon?"
    e "I wanted to ask if you'd like to come with me after rehearsals to the Greenhouse."
    e "Or anywhere, really, if you don't feel like going to the Greenhouse."

    "I can feel Professor Morgana's stare from here."
    menu:
	"You should prioritize practicing for the ritual since it's tomorrow.":
            e "I see..."
    	    "She sigh deeply."
	    "I hope I didn't upset her."
	    e "You're right."
	    e "I can't get too distracted now."
	    e "I need to make sure the ritual runs smoothly!"
	    e "Plus, we can always go out after it's over" #Copyedited says "... go out after the it's over."
	    char "Go out?"
	    e "Ah!"
	    e "I meant like-"
	    e "Just go out somewhere to celebrate the successes of the Full Moon Ritual, you know?"
	    e "I should go back and practice."
	    e "I'll catch you back at the Commons!"
	    "Eluna briskly walks away."
	"I actually have an assignment that I have to finish tonight.":
	    e "Oh, okay."
	    e "It's good to focus on your studies."
	    e "I should focus on practicing for the ritual anyways."
	    e "I can't get too distracted now."
	    e "I need to make sure it runs smoothly!"
	    e "I should go back to rehearsing."
	    e "I'll see you back at the Commons."
	    char "Yeah I'll catch you later."
	    "Eluna walks back to the Amphitheater stage."
	"I'd love to, but I can't I'll meet you in the Commons.":
	    e "But you just got here!"
	    e "You still have an obligation to stay for class or do schoolwork."
	    "The air around us feels like crackling electricity."
	    e "Is there something going on?"
	    m "That's quite enough, Eluna." #Added a comma
	    "Professor Morgana appears besides us."
	    m "Eluna, you should go continue rehearsing for tomorrow evening's ritual."
	    e "I'm sorry, Professor Morgana."
	    e "I should focus on practicing."
	    e "I can't afford any distractions."
	    "Eluna walks off to the Amphitheater stage."
	    "I sigh."
	    m "You can leave early if you must."
	    m "I must go back to attend to class."
	    "Before I could respond, Professor Morgana strides away."

    "I guess I'll go back to my room to read or study for a little bit."
    "I need to clear my head."
    "I leave the Amphitheater and head towards the Commons."
    "I do want to continue watching and helping out Eluna-"
    "But I don't want to further distract her, and the Ritual must go well."
    "As I make my exit, I look back at the stage-"
    "Eluna glances at me, and waves."
    "I wave back, and make my way back to the Commons."

    ##hide Scene with Fade