label day3Stella:
    "Huh, I'm in my room."
    "The last thing I remember was studying with Celeste..."
    "Oh no, I must've fallen asleep!"
    "How did I get in my room anyways...?"
    c "Hello? [name]?"
    c "Are you alright in there?"
    char "Y-yes, give me a second."
    scene Commons with Fade(2.0, 1.0, 2.0)
    "I dash out to the Commons."
    char "I'm sorry, I'm not sure what happened."
    c "Oh, no worries."
    c "You passed out after an hour of reading."
    c "You seemed to have really fallen asleep, so I took you back."
    "Did she carry me? Is she that strong?"
    c "I'm not as adept as Eluna in my magical prowess-"
    c "But I managed to do some short transportation hops across campus."
    char "I'm so sorry, that must've been really out of the way for you."
    c "I actually thought it was really funny you fell asleep."
    c "You've gotta learn to keep up with me."

    c "Speaking of keeping up..."
    c "I wanted to go to the Greenhouse today to check out the flowers."
    c "Flower language can be quite important, and it may be useful in understanding Luminoire much better."
    char "Ah, I see."
    c "Hurry up and get ready to go out."
    c "I'll wait here in the Commons for you."
    char "Got it, it'll only be a minute."
    "I scramble to get ready for the day."
    "I've already got a quest to do!"

    "After freshening up, I go find Celeste in the Commons."
    "When Celeste notices me, she closes the book she's reading."
    c "Ready to go?"
    char "Ready when you are."
    c "Great!"
    c "Let's go to the Greenhouse."

    ##scene Greenhouse with Fade(2.0, 0.0, 2.0) Celeste: Here we are!
    c "Although the Greenhouse isn't as precisely organized as the library-"
    c "-there's a certain charm to its...organized mess."
    t "Are you bad-mouthing my Greenhouse?"
    c "P-professor Tasha!"
    ##show tashaNeutral at right with move 
    c "It's not bad-mouthing, it's just an observation I've made."
    t "I'm just joking, no need to take me so seriously."
    t "I was just about to head out for lunch, so if you need anything, ask Summer."
    c "Got it!"
    "Professor Tasha looks over at me."
    t "Make sure her head is screwed on, alright?"
    ##show celesteUpsetB
    "Tasha leaves the Greenhouse, chuckling to herself."
    c "I can't believe she heard me say that..."
    s "You're not exactly good at keeping all your observations to yourself, you know?"

    ##show summerNeutral at right with move 
    s "You really should work on that, some people can take it the wrong way."
    c "The opinions of others are not of primary concern."
    "Summer sighs deeply."
    s "It's not about being concerned of other people's opinions."
    s "Nevermind that, what're you up to in the Greenhouse?"
    c "I wanted to do some research in flower language."
    "Celeste holds up the book she was reading earlier in the Commons."
    c "I found a book that explains a little bit on flower language, and wanted to do some research on what Luminoire's native flowers were."
    s "Well, you're in luck!"
    s "The garden outside has just bloomed with some beautiful seasonals."
    s "You can go take a look-"
    s "-just don't fall over into the bushes again."
    c "You..."
    ##show celesteUpsetB
    char "Did something happen before?"
    s "Well-"
    c "No!"
    c "Nothing happened."
    c "I'm going to be in the garden for a bit."
    "Celeste briskly leaves the Greenhouse."

    s "Celeste is really something, isn't she?"
    menu:
        "She really is.":
            s "Oh?"
            s "You'd better hope she didn't hear you say that."
            s "She normally isn't okay with teasing."
            s "We're pretty close, so I'm not so concerned with her perception of me-"
            s "-as it's been established a while ago."
            "Summer looks out the window to where Celeste is and sighs."
            s "It's funny..."
            s "Despite Celeste and I being the same age and year-"
            s "- She puts {i}so{/i} much pressure on herself to be more knowledgeable than any other witch here."
            s "Make sure you watch over her, okay?"
            "Watch over her?"
            "I wonder what she means by that..."
        "What do you mean?":
            s "She takes herself so seriously."
            s "I wish she'd think about just decompressing for a little bit."
            s "I'm glad though that she's taken a liking to you."
            char "You think she has?"
            s "Oh yeah."
            s "It might seem like she's just dragging you along for her research-"
            s "-And you wouldn't be wrong on that presumption-"
            s "-but, much like research, consistency is key."
            s "I hope you continue to take care of her."
            "Take care of her?"
            "I wonder what she means by that..."
    
    c "[name]! [name]!"
    "She dashes into the Greenhouse, nearly out of breath."
    c "I've made some incredible observations!"
    c "I've jotted them all down in my notebook, I'll show it to you later."
    s "Well you certainly seem excited."
    c "The garden was especially beautiful today."
    c "I've brought some flowers with me too."
    if celesteAP >= 3:
        c "Here, I picked one for you!"
        "She hands me a vibrant violet."
        c "Isn't this such a perfect flower?"
        char "Yeah, it's very pretty."
        "I can feel Summer peering over at us..."
        "My face feels really warm..."
        s "That's very sweet of you to do, Celeste."
    else:
        s "Oh, you picked flowers from the garden?"
        c "There were so many, I'm sure it's fine."
        s "Alright, but next time please as first."
        c "Got it!"
        c "Sorry, Summer. I know how much that bothers you."
        c "The results will be worth it, I swear!"
        s "Alright..."
    
    c "We should head back to the Commons."
    "Celeste tightens her grip on the book."
    c "There's a lot I need to tell you!"
    s "Don't trip on your way back."
    "Celeste makes her way out of the Greenhouse."
    "I turn to follow her and-"
    s "Remember what I told you."
    "I look back at Summer."
    "Her stare is unwavering."
    s "Have fun!"
    "Summer briskly leaves the Greenhouse as well, making her way to the garden."
    "Well, that was an eventful day."
    "I need to catch up with Celeste..."
    char "Wait up!"